services:
    a-township-container:
        build: .
        container_name: a-township-container
        restart: unless-stopped
        # Uncomment the following lines to limit CPU and memory usage
        # cpus: 2
        # mem_limit: 4g
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./game-source:/game-files
            - ./server-data:/root/.wine/drive_c/users/root/AppData/Roaming/A Township Tale
            - ./tavern-config:/root/.wine/drive_c/users/root/AppData/Roaming/TheModdingTavern
            - wine-prefix:/root/.wine
        ports:
            # gameserver
            - '${SERVER_PORT:-1757}:${SERVER_PORT:-1757}/udp'
            - '${SERVER_PORT:-1757}:${SERVER_PORT:-1757}/tcp'
            # rcon
            - '${RCON_PORT:-1758}:${RCON_PORT:-1758}/udp'
            - '${RCON_PORT:-1758}:${RCON_PORT:-1758}/tcp'
            # forest
            - '${FOREST_PORT:-1761}:${FOREST_PORT:-1761}/udp'
            - '${FOREST_PORT:-1761}:${FOREST_PORT:-1761}/tcp'
            # authentication
            - '${AUTH_PORT:-1762}:${AUTH_PORT:-1762}/udp'
            - '${AUTH_PORT:-1762}:${AUTH_PORT:-1762}/tcp'
        environment:
            SERVER_PORT: ${SERVER_PORT:-1757}
            AUTO_PATCH: ${AUTO_PATCH:-true}
            DEBUG: ${DEBUG:-false}
            ATT_ACCESS_TOKEN: ${ATT_ACCESS_TOKEN:-}
            ATT_REFRESH_TOKEN: ${ATT_REFRESH_TOKEN:-}
            ATT_IDENTITY_TOKEN: ${ATT_IDENTITY_TOKEN:-}

volumes:
    wine-prefix:
